### ISSUE TITLE
Loading WPC CSV

### ISSUE THREAD

**Issue by brettmcc** [ActivismTechnologiesFoundation/assemble-web#1]
There seems to be an issue in loading the CSV in that because most addresses don't have a 2nd line, the zip code fills in that field (as seen on the [events API](http://www.assembleapp.org/api/events)), so that the actual zip code field is null. I think this explains the needless comma's after zip codes in the display. 

Let Brett know if there's something he should do differently in formatting the data.

**Comment by rpc4mv** [comment]
This was a bug with the csv event loading code / data. Just have to make sure the csv has a column for "line_2" even if it's blank.
