### ISSUE TITLE
submission form fonts

### ISSUE THREAD

**Issue by brettmcc** [ActivismTechnologiesFoundation/assemble-web#14]
description font different than others; make all uniform

**Comment by rpc4mv** [comment]
The font's are the same so I'm not sure what this refers to

**Comment by brettmcc** [comment]
![event submission](https://cloud.githubusercontent.com/assets/12285230/12045911/d01f3458-ae7a-11e5-8c54-f1735c4188f6.png)
This is what I see in Firefox 43.0.1 on Windows 10.

**Comment by brettmcc** [comment]
I looked again and all the fonts are uniform.
